# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserEditor.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserEditWin(object):
    def setupUi(self, UserEditWin):
        UserEditWin.setObjectName("UserEditWin")
        UserEditWin.resize(900, 450)
        UserEditWin.setMinimumSize(QtCore.QSize(900, 450))
        UserEditWin.setMaximumSize(QtCore.QSize(900, 450))
        self.centralwidget = QtWidgets.QWidget(UserEditWin)
        self.centralwidget.setObjectName("centralwidget")
        self.addBtnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.addBtnEdit.setGeometry(QtCore.QRect(220, 30, 90, 35))
        self.addBtnEdit.setObjectName("addBtnEdit")
        self.editBtnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.editBtnEdit.setGeometry(QtCore.QRect(220, 80, 90, 35))
        self.editBtnEdit.setObjectName("editBtnEdit")
        self.lstboxUsers = QtWidgets.QListWidget(self.centralwidget)
        self.lstboxUsers.setGeometry(QtCore.QRect(10, 30, 180, 150))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lstboxUsers.setFont(font)
        self.lstboxUsers.setObjectName("lstboxUsers")
        self.lstboxUserGroup = QtWidgets.QListWidget(self.centralwidget)
        self.lstboxUserGroup.setGeometry(QtCore.QRect(10, 220, 180, 150))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lstboxUserGroup.setFont(font)
        self.lstboxUserGroup.setObjectName("lstboxUserGroup")
        self.lblUser = QtWidgets.QLabel(self.centralwidget)
        self.lblUser.setGeometry(QtCore.QRect(10, 10, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblUser.setFont(font)
        self.lblUser.setObjectName("lblUser")
        self.lblGroup = QtWidgets.QLabel(self.centralwidget)
        self.lblGroup.setGeometry(QtCore.QRect(10, 196, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblGroup.setFont(font)
        self.lblGroup.setObjectName("lblGroup")
        self.lstboxUsersInGroup = QtWidgets.QListWidget(self.centralwidget)
        self.lstboxUsersInGroup.setGeometry(QtCore.QRect(240, 220, 180, 150))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lstboxUsersInGroup.setFont(font)
        self.lstboxUsersInGroup.setObjectName("lstboxUsersInGroup")
        self.userInfoBtnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.userInfoBtnEdit.setGeometry(QtCore.QRect(220, 130, 90, 35))
        self.userInfoBtnEdit.setObjectName("userInfoBtnEdit")
        self.lblUserGroup = QtWidgets.QLabel(self.centralwidget)
        self.lblUserGroup.setGeometry(QtCore.QRect(240, 195, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblUserGroup.setFont(font)
        self.lblUserGroup.setObjectName("lblUserGroup")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 30, 220, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(560, 30, 220, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lblinfoUsername = QtWidgets.QLabel(self.centralwidget)
        self.lblinfoUsername.setGeometry(QtCore.QRect(330, 10, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblinfoUsername.setFont(font)
        self.lblinfoUsername.setObjectName("lblinfoUsername")
        self.lblinfoPassword = QtWidgets.QLabel(self.centralwidget)
        self.lblinfoPassword.setGeometry(QtCore.QRect(560, 10, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblinfoPassword.setFont(font)
        self.lblinfoPassword.setObjectName("lblinfoPassword")
        self.chbAddUser = QtWidgets.QCheckBox(self.centralwidget)
        self.chbAddUser.setGeometry(QtCore.QRect(330, 80, 240, 20))
        self.chbAddUser.setObjectName("chbAddUser")
        self.chbAddUserGroup = QtWidgets.QCheckBox(self.centralwidget)
        self.chbAddUserGroup.setGeometry(QtCore.QRect(330, 110, 240, 20))
        self.chbAddUserGroup.setObjectName("chbAddUserGroup")
        self.chbAddUserToGroup = QtWidgets.QCheckBox(self.centralwidget)
        self.chbAddUserToGroup.setGeometry(QtCore.QRect(330, 140, 240, 20))
        self.chbAddUserToGroup.setObjectName("chbAddUserToGroup")
        UserEditWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UserEditWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        UserEditWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UserEditWin)
        self.statusbar.setObjectName("statusbar")
        UserEditWin.setStatusBar(self.statusbar)

        self.retranslateUi(UserEditWin)
        QtCore.QMetaObject.connectSlotsByName(UserEditWin)

    def retranslateUi(self, UserEditWin):
        _translate = QtCore.QCoreApplication.translate
        UserEditWin.setWindowTitle(_translate("UserEditWin", "MainWindow"))
        self.addBtnEdit.setText(_translate("UserEditWin", "Add"))
        self.editBtnEdit.setText(_translate("UserEditWin", "Edit"))
        self.lblUser.setText(_translate("UserEditWin", "All Users"))
        self.lblGroup.setText(_translate("UserEditWin", "All User Groups"))
        self.userInfoBtnEdit.setText(_translate("UserEditWin", "Show User Info"))
        self.lblUserGroup.setText(_translate("UserEditWin", "Users in group"))
        self.lblinfoUsername.setText(_translate("UserEditWin", "Username"))
        self.lblinfoPassword.setText(_translate("UserEditWin", "Password"))
        self.chbAddUser.setText(_translate("UserEditWin", "Add User"))
        self.chbAddUserGroup.setText(_translate("UserEditWin", "Add User Group"))
        self.chbAddUserToGroup.setText(_translate("UserEditWin", "Add selected User to selected User Group"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserEditWin = QtWidgets.QMainWindow()
    ui = Ui_UserEditWin()
    ui.setupUi(UserEditWin)
    UserEditWin.show()
    sys.exit(app.exec_())
